version: "3"

services:
  postgres:
    image: postgres:9.6.2
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data

  redis:
    image: redis:3.2
    command: redis-server
    ports:
      - "6379:6379"
    volumes:
      - redis:/var/lib/redis/data

  nginx:
    build:
      context: .
      dockerfile: docker/Dockerfile.nginx
    ports:
      - 80:80

  web:
    depends_on:
      - postgres
      - redis
      - nginx
    build:
      context: .
      dockerfile: docker/Dockerfile.prod
    volumes:
      - .:/sample_docker_app
    env_file: .env
    expose:
      - "3000"
    environment:
      RAILS_ENV: production
      RACK_ENV: production
      DATABASE_HOST: postgres

  sidekiq:
    depends_on:
      - postgres
      - redis
    build:
      context: .
      dockerfile: docker/Dockerfile.prod
    command: sidekiq -C config/sidekiq.yml
    volumes:
      - .:/sample_docker_app
    environment:
      RAILS_ENV: production
      RACK_ENV: production
      DATABASE_HOST: postgres

  crono:
    depends_on:
      - postgres
      - redis
    build:
      context: .
      dockerfile: docker/Dockerfile.prod
    command: bundle exec crono
    environment:
      RAILS_ENV: production
      RACK_ENV: production
      DATABASE_HOST: postgres

volumes:
  postgres:
  redis:
