version: "3"

services:
  postgres:
    image: postgres:9.6.2
    ports:
      - "5433:5432"
    volumes:
      - postgres:/var/lib/postgresql/data

  redis:
    image: redis:3.2
    command: redis-server
    ports:
      - "6379:6379"
    volumes:
      - redis:/var/lib/redis/data

  web:
    depends_on:
      - postgres
      - redis
    build:
      context: .
      dockerfile: docker/development/Dockerfile
    volumes:
      - .:/sample_docker_app
    env_file:
      - .env
    ports:
      - "3333:3000"
    environment:
      DATABASE_HOST: postgres

  sidekiq:
    depends_on:
      - postgres
      - redis
    build:
      context: .
      dockerfile: docker/development/Dockerfile
    command: sidekiq -C config/sidekiq.yml
    volumes:
      - .:/sample_docker_app
    environment:
      DATABASE_HOST: postgres

  crono:
    depends_on:
      - postgres
      - redis
    build:
      context: .
      dockerfile: docker/development/Dockerfile
    command: bundle exec crono
    environment:
      DATABASE_HOST: postgres

volumes:
  postgres:
  redis:
