FROM nginx

RUN apt-get update -qq && apt-get -y install apache2-utils
ENV APP_PATH /sample-docker-app
WORKDIR $APP_PATH

RUN mkdir log
COPY public public/
COPY config/nginx.conf /tmp/sample_docker_app.nginx

RUN envsubst '$APP_PATH' < /tmp/sample_docker_app.nginx > /etc/nginx/conf.d/default.conf

CMD [ "nginx", "-g", "daemon off;" ]
